version: '3.7'

services:
  adminer:
    restart: "${RESTART}"
    image: ${IMAGE}:latest
    container_name: ${SERVICE_NAME}
    # ports:
    # - "80:80"
    # - "443:443"
    volumes:
      - ./etc/php5/php.ini:/etc/php5/php.ini
    labels:
      - "traefik.enable=true"
      - "traefik.port=80"
      - "traefik.frontend.rule=Host:${SERVICE_NAME}.${SERVICE_DOMAIN}"
    networks:
      - traefik.bridge

networks:
  traefik.bridge:
    external:
      name: "${DOCKER_NETWORK}"
